version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LUNATICOIN_PRICE_ORACLE_IP}
      APP_PORT: ${APP_LUNATICOIN_PRICE_ORACLE_PORT}
      PROXY_AUTH_ADD: "false"

  oracle:
    image: ghcr.io/lunaticoin/bitcoin-price-oracle:v0.1.11@sha256:8434f8ec2b5a2b66f2d471a7816e79671236abe20f730ffe2e3f2e9895167958
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    environment:
      RPC_HOST: ${APP_BITCOIN_NODE_IP}
      RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      RPC_USER: ${APP_BITCOIN_RPC_USER}
      RPC_PASS: ${APP_BITCOIN_RPC_PASS}
      BLOCKS_DIR: /bitcoin/blocks
      DATA_DIR: /data
      PORT: "3200"
      CORS_ENABLED: "false"
      APP_HIDDEN_SERVICE: ${APP_HIDDEN_SERVICE}
    networks:
      default:
        ipv4_address: ${APP_LUNATICOIN_PRICE_ORACLE_IP}
