version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LUNATICOIN_PRICE_ORACLE_IP}
      APP_PORT: ${APP_LUNATICOIN_PRICE_ORACLE_PORT}
      PROXY_AUTH_ADD: "false"

  oracle:
    image: ghcr.io/lunaticoin/bitcoin-price-oracle:v0.1.5@sha256:0030f5c598d5e7d0be61046cf18fdf15e1b1a9eb75439aef356a265dfa05abf8
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    environment:
      RPC_HOST: ${APP_BITCOIN_NODE_IP}
      RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      RPC_USER: ${APP_BITCOIN_RPC_USER}
      RPC_PASS: ${APP_BITCOIN_RPC_PASS}
      BLOCKS_DIR: /bitcoin/blocks
      DATA_DIR: /data
      PORT: "3200"
    networks:
      default:
        ipv4_address: ${APP_LUNATICOIN_PRICE_ORACLE_IP}
