version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LUNATICOIN_PRICE_ORACLE_IP}
      APP_PORT: ${APP_LUNATICOIN_PRICE_ORACLE_PORT}
      PROXY_AUTH_ADD: "false"

  oracle:
    image: ghcr.io/lunaticoin/bitcoin-price-oracle:v0.1.0@sha256:82309e162ad24e81c03ae755cd5f9fd85b8dad5b8de7ee8400431bc218642987
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      RPC_HOST: ${APP_BITCOIN_NODE_IP}
      RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      RPC_USER: ${APP_BITCOIN_RPC_USER}
      RPC_PASS: ${APP_BITCOIN_RPC_PASS}
      DATA_DIR: /data
      PORT: "3200"
    networks:
      default:
        ipv4_address: ${APP_LUNATICOIN_PRICE_ORACLE_IP}
