version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_LUNATICOIN_BRK_IP}
      APP_PORT: ${APP_LUNATICOIN_BRK_PORT}
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/lunaticoin/brk:v0.2.5@sha256:2ce31209c074999b33461e319ac47bf9d631cdeba8d6632e52810f1996bbd1b6
    init: true
    restart: on-failure
    stop_grace_period: 5m
    volumes:
      - ${APP_DATA_DIR}/data:/home/brk/.brk
      - ${APP_BITCOIN_DATA_DIR}:/bitcoin:ro
    command:
      - --bitcoindir
      - /bitcoin
      - --blocksdir
      - /bitcoin/blocks
      - --brkdir
      - /home/brk/.brk
      - --rpcconnect
      - "${APP_BITCOIN_NODE_IP}"
      - --rpcport
      - "${APP_BITCOIN_RPC_PORT}"
      - --rpcuser
      - "${APP_BITCOIN_RPC_USER}"
      - --rpcpassword
      - "${APP_BITCOIN_RPC_PASS}"
    networks:
      default:
        ipv4_address: ${APP_LUNATICOIN_BRK_IP}
